var team = [
    {
        'name': 'Ysabelle David',
        'role': 'CEO & COO',
        'teacher': 'True',
        'image': 'assets/img/VSr Team Photos/Ysabelle David.jpg',
        'socials': [
            {'fb': 'https://www.facebook.com/ysabelledavid1005'},
            {'ig': 'https://www.instagram.com/iamysabelle.d/'},
            {'in': 'http://www.linkedin.com/in/ysabellerdavid'},
        ],
        'site': 'https://www.ysabelledavid.com',
        'description': `Writer by passion🖊️  VA and nerd by choice. 🤓 <br>
        Aspiring Philanthropist and extremely organized. Made the switch ⚡ 2 years ago.<br>
        I also have a Monkey companion in life. 🐒`,
    },
    {
        'name': 'Junny Cerdeña',
        'role': 'President',
        'teacher': 'True',
        'image': 'assets/img/VSr Team Photos/Junny Cerdeña.jpg',
        'socials': [
            {'fb': 'https://www.facebook.com/junnette.cerdena'},
            {'ig': 'https://www.linkedin.com/in/virtually-junny/'},
            {'in': 'https://www.instagram.com/virtuallyjunny/'},
        ],
        'site': 'https://www.virtuallyjunny.com',
        'description': `Former Food Technologist who decided to "Make the Switch" back in 2018. Since then, Junny has been a Virtual Assistant specializing in Administrative and Technical Roles. Tech whiz🤓 + Organizing freak. `,
    },
    {
        'name': 'Krishma Kishore',
        'role': 'Customer Support',
        'teacher': 'False',
        'image': 'assets/img/VSr Team Photos/Maki Kishore.jpg',
        'socials': [
            {'fb': 'https://www.facebook.com/akosikrishma'},
            {'ig': 'https://instagram.com/akosikrishma?igshid=jkfdn5h4l4cg'},
            {'in': 'https://twitter.com/akosikrishma'},
        ],
        'site': '',
        'description': `Got tired of my 12-hour shifts, and decided to make the switch. 🤘🏻 Functioning well when caffeinated. Financial literacy advocate. I probably enjoy memes more than the average person. `,
    },
    {
        'name': 'Stef Arellano-Rañosa',
        'role': 'Ads Specialist',
        'teacher': 'True',
        'image': 'assets/img/VSr Team Photos/Stef Arellano-Rañosa.jpg',
        'socials': [
            {'fb': 'https://www.facebook.com/S.Dawn.A.Ranosa/'},
            {'ig': 'https://www.instagram.com/s.dawn.21/'},
            {'in': 'https://www.linkedin.com/in/stephanie-dawn-arellano-ra%C3%B1osa-a2b03bba/'},
        ],
        'site': '',
        'description': `Customer Service Champion. Social Media Manager. Mother of Cats.🐱`,
    },
    {
        'name': 'Ja Casanova-Garrido',
        'role': 'SEO Specialist',
        'teacher': 'True',
        'image': 'assets/img/VSr Team Photos/Ja Casanova-Garrido.jpg',
        'socials': [
            {'fb': 'https://www.facebook.com/janine.casanova'},
            {'ig': ''},
            {'in': ''},
        ],
        'site': '',
        'description': `A mom of 2 boys. Passionate and dedicated. Loves travel, have fun and collect memories with her family and friends. Was a BPO employee for 10 years combined. Also a Car Sales agent. Now practicing skills in SEO. `,
    },
    {
        'name': 'Tatyana Gonzaga',
        'role': 'Web Developer',
        'teacher': 'False',
        'image': 'assets/img/VSr Team Photos/Tatyana Gonzaga.JPG',
        'socials': [
            {'fb': ''},
            {'ig': 'https://www.instagram.com/tatyana.gonzaga/'},
            {'in': ''},
        ],
        'site': 'https://www.linkedin.com/in/tatyanagonzaga/',
        'description': `I code for a living, but mostly for marketing. I brew coffee at home like a professional. I care for plants like they are my babies.`,
    },
    {
        'name': 'RJ Garrido',
        'role': 'Video Editor',
        'teacher': 'False',
        'image': 'assets/img/VSr Team Photos/RJ Garrido.jpg',
        'socials': [
            {'fb': 'https://www.facebook.com/arjae.garrido'},
            {'ig': ''},
            {'in': ''},
        ],
        'site': '',
        'description': `Former Starbucks Barista, Front Desk Officer turned Video Editor. A father of 2 and an aspiring "plantito". `,
    },
    {
        'name': 'Jan Rey Cerdeña',
        'role': 'Graphic Designer',
        'teacher': 'False',
        'image': 'assets/img/VSr Team Photos/Jan Rey Cerdeña.jpg',
        'socials': [
            {'fb': ''},
            {'ig': ''},
            {'in': 'https://www.linkedin.com/in/janrey-cerdena/'},
        ],
        'site': 'https://www.linkedin.com/in/janrey-cerdena/',
        'description': `Designer. Looking forward to do more gaming and streaming related designs in the future. I like good music and playing video games with friends.`,
    },
];
